### PR TITLE
Update research.md

### PR DESCRIPTION
**Pull request by gavinly**

### CODE REVIEW

**Comment by hxrts** [comment]
Thanks for the copy edits @gavinly! Really appreciate it. I'd merge this right away, but we *may* need to have edits explicitly approved by the ICF council first (lol), will confirm. cc @okwme

**Comment by okwme** [comment]
yes thank you @gavinly , would you want to make the base branch into https://github.com/interchainio/funding/pull/10?

**Comment by gavinly** [comment]
> yes thank you @gavinly , would you want to make the base branch into #10?

As a Github newb, I don't know how to confidently do that :)

**Comment by hxrts** [comment]
Suggested same change in #10 

@gavinly here's a link to instructions about how to make inline changes to PRs if you're interested: https://haacked.com/archive/2019/06/03/suggested-changes/

Unrelated, would also be great to sync up at some point to discuss how the Governance Working Group and ICF can play well together, will send you an email in a min.

**Pull request closed without merging**
